Repository ALTA-CAPSTONE-GROUP1-SirloinPOSApp/sirloinAPI, pull requests merged in 2023-02, with the labels that each got.

#23 test: unit testing feature user services (#22)
  features/user/services/service_test.go
Labels: enhancement

#32 Feature/transaction addbuy
  features/transaction/data/query.go
  features/transaction/entity.go
  features/transaction/handler/handler.go
  features/transaction/services/services.go
  main.go
Labels: enhancement

#34 prefix: fix featurure/transaction (#33)
  features/transaction/data/query.go
  main.go
Labels: bug

#42 test: unit test feature transaction addSell sevice (#38) and addBuy s…
  features/transaction/services/service_test.go
  mocks/TransactionData.go
  mocks/TransactionHandler.go
  mocks/TransactionService.go
Labels: enhancement

#51 Features/customer
  features/customer/data/model.go
  features/customer/data/query.go
  features/customer/entity.go
  features/customer/handler/handler.go
  features/customer/handler/request.go
  features/customer/services/service.go
  features/user/handler/handler.go
  features/user/handler/request.go
  helper/response.go
  helper/validasi.go
  main.go
Labels: enhancement

#60 Features/customer
  features/customer/data/query.go
  features/customer/entity.go
  features/customer/handler/handler.go
  features/customer/handler/response.go
  features/customer/services/service.go
  features/user/services/service.go
  go.mod
  go.sum
  helper/jwt.go
  helper/validasi.go
  main.go
Labels: enhancement

#61 Features/customer
  features/customer/data/model.go
  features/customer/data/query.go
  features/customer/entity.go
  features/customer/handler/handler.go
  features/customer/handler/response.go
  features/customer/services/service.go
  main.go
Labels: enhancement

#62 Feature/user fix
  features/customer/handler/handler.go
  features/customer/services/service.go
  features/customer/services/service_test.go
  features/product/services/service_test.go
  features/transaction/services/service_test.go
  features/user/handler/handler.go
  features/user/services/service_test.go
  helper/response.go
  mocks/CustomerData.go
  mocks/CustomerHandler.go
  mocks/CustomerService.go
Labels: enhancement

#63 Feature/customer unit testing
  features/customer/handler/handler.go
  features/customer/services/service_test.go
  features/user/handler/handler.go
Labels: enhancement

#66 Admintranshist
  features/transaction/data/query.go
  features/transaction/entity.go
  features/transaction/handler/handler.go
  features/transaction/response.go
  features/transaction/services/services.go
  main.go
  mocks/TransactionData.go
  mocks/TransactionHandler.go
  mocks/TransactionService.go
Labels: enhancement

#76 fix: fixed upload image product to aws s3
  helper/upload_s3.go
Labels: bug

#85 Createpdf generator
  .DS_Store
  .gitignore
  features/transaction/data/query.go
  features/transaction/services/services.go
  go.mod
  go.sum
  helper/create-pdf.go
Labels: duplicate

#87 feat: uoload report pdf to aws 3 bucket
  features/transaction/entity.go
  features/transaction/handler/handler.go
  features/transaction/services/services.go
Labels: enhancement

#89 Gitkeep folderksosong
  .gitignore
  features/transaction/services/reports/.gitkeep
  features/transaction/services/services.go
  helper/create-pdf.go
Labels: bug

#91 fix: add 1 day for query (to)
  features/transaction/data/query.go
Labels: bug

#92 replace string format use (/) to (-)
  features/transaction/data/query.go
Labels: bug

#99 Refactor and send report via emal
  features/transaction/data/query.go
  features/transaction/entity.go
  features/transaction/services/services.go
Labels: enhancement

#114 Feature/transaction check stock product before add to cart
  features/transaction/data/query.go
  features/transaction/handler/handler.go
  features/transaction/services/services.go
Labels: enhancement

#123 fix: error handling and coloring log text
  features/transaction/data/query.go
Labels: bug
